In [1]:
# Import some common packages
import os
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import pandas as pd

# to make this notebook's output stable across runs
np.random.seed(42)

DATA_PATH = '.'

def load_data(data_path=DATA_PATH, filename="gun-violence-data_01-2013_03-2018.csv"):
    csv_path = os.path.join(data_path, filename)
    return pd.read_csv(csv_path, error_bad_lines=False)

poverty_data = load_data(DATA_PATH, "poverty.csv")
education_data = load_data(DATA_PATH, "education.csv")
unemployment_data = load_data(DATA_PATH, "unemployment.csv")
population_data = load_data(DATA_PATH, "population.csv")
# drop states and US because we want to get the data by county
poverty_data = poverty_data.dropna(subset=["Rural-urban_Continuum_Code_2013", "Urban_Influence_Code_2013"]) 
education_data = education_data.dropna(subset=["2013 Rural-urban Continuum Code", "2013 Urban Influence Code"])
unemployment_data = unemployment_data.dropna(subset=["Rural_urban_continuum_code_2013", "Urban_influence_code_2013"])
population_data = population_data.dropna(subset=["Rural-urban_Continuum Code_2013", "Urban_Influence_Code_2013","POP_ESTIMATE_2017",
                                                "POP_ESTIMATE_2016","POP_ESTIMATE_2015","POP_ESTIMATE_2014","POP_ESTIMATE_2013"])

poverty_data.head()

,FIPStxt,State,Area_Name,Rural-urban_Continuum_Code_2003,Urban_Influence_Code_2003,Rural-urban_Continuum_Code_2013,Urban_Influence_Code_2013,POVALL_2016,CI90LBAll_2016,CI90UBALL_2016,...,CI90UB517P_2016,MEDHHINC_2016,CI90LBINC_2016,CI90UBINC_2016,POV05_2016,CI90LB05_2016,CI90UB05_2016,PCTPOV05_2016,CI90LB05P_2016,CI90UB05P_2016
2,1001,AL,Autauga County,2.0,2.0,2.0,2.0,"7,444","6,255","8,633",...,22.0,"54,487","50,886","58,088",NaN,NaN,NaN,NaN,NaN,NaN
3,1003,AL,Baldwin County,4.0,5.0,3.0,2.0,"24,005","20,132","27,878",...,20.0,"56,460","53,250","59,670",NaN,NaN,NaN,NaN,NaN,NaN
4,1005,AL,Barbour County,6.0,6.0,6.0,6.0,"6,787","5,551","8,023",...,45.0,"32,884","29,684","36,084",NaN,NaN,NaN,NaN,NaN,NaN
5,1007,AL,Bibb County,1.0,1.0,1.0,1.0,"4,099","3,194","5,004",...,33.0,"43,079","38,896","47,262",NaN,NaN,NaN,NaN,NaN,NaN
6,1009,AL,Blount County,1.0,1.0,1.0,1.0,"8,033","6,506","9,560",...,22.0,"47,213","43,017","51,409",NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
education_data.head()

,FIPS Code,State,Area name,2003 Rural-urban Continuum Code,2003 Urban Influence Code,2013 Rural-urban Continuum Code,2013 Urban Influence Code,"Less than a high school diploma, 1970","High school diploma only, 1970","Some college (1-3 years), 1970",...,"Percent of adults completing some college or associate's degree, 2000","Percent of adults with a bachelor's degree or higher, 2000","Less than a high school diploma, 2012-2016","High school diploma only, 2012-2016","Some college or associate's degree, 2012-2016","Bachelor's degree or higher, 2012-2016","Percent of adults with less than a high school diploma, 2012-2016","Percent of adults with a high school diploma only, 2012-2016","Percent of adults completing some college or associate's degree, 2012-2016","Percent of adults with a bachelor's degree or higher, 2012-2016"
2,1001,AL,Autauga County,2.0,2.0,2.0,2.0,"6,611","3,757",933,...,26.9,18.0,"4,528","12,519","10,451","8,968",12.4,34.3,28.7,24.6
3,1003,AL,Baldwin County,4.0,5.0,3.0,2.0,"18,726","8,426","2,334",...,29.3,23.1,"13,956","40,154","44,486","41,350",10.0,28.7,31.8,29.5
4,1005,AL,Barbour County,6.0,6.0,6.0,6.0,"8,120","2,242",581,...,21.3,10.9,"4,824","6,422","4,775","2,366",26.2,34.9,26.0,12.9
5,1007,AL,Bibb County,1.0,1.0,1.0,1.0,"5,272","1,402",238,...,20.4,7.1,"3,040","6,586","4,234","1,890",19.3,41.8,26.9,12.0
6,1009,AL,Blount County,1.0,1.0,1.0,1.0,"10,677","3,440",626,...,24.8,9.6,"7,882","13,003","13,436","5,151",20.0,32.9,34.0,13.1

In [3]:
unemployment_data.head()

,FIPStxt,State,Area_name,Rural_urban_continuum_code_2013,Urban_influence_code_2013,Metro_2013,Civilian_labor_force_2007,Employed_2007,Unemployed_2007,Unemployment_rate_2007,...,Civilian_labor_force_2016,Employed_2016,Unemployed_2016,Unemployment_rate_2016,Civilian_labor_force_2017,Employed_2017,Unemployed_2017,Unemployment_rate_2017,Median_Household_Income_2016,Med_HH_Income_Percent_of_State_Total_2016
2,1001,AL,"Autauga County, AL",2.0,2.0,1.0,"24,383","23,577",806,3.3,...,"25,918","24,593","1,325",5.1,25909,24908,1001,3.9,"$54,487",117.7
3,1003,AL,"Baldwin County, AL",3.0,2.0,1.0,"82,659","80,099","2,560",3.1,...,"90,500","85,656","4,844",5.4,91567,87915,3652,4.0,"$56,460",121.9
4,1005,AL,"Barbour County, AL",6.0,6.0,0.0,"10,334","9,684",650,6.3,...,"8,402","7,700",702,8.4,8236,7750,486,5.9,"$32,884",71.0
5,1007,AL,"Bibb County, AL",1.0,1.0,1.0,"8,791","8,432",359,4.1,...,"8,607","8,050",557,6.5,8506,8133,373,4.4,"$43,079",93.0
6,1009,AL,"Blount County, AL",1.0,1.0,1.0,"26,629","25,780",849,3.2,...,"24,576","23,248","1,328",5.4,24494,23509,985,4.0,"$47,213",102.0

In [4]:
# drop the state in "Area_name"
unemployment_data["Area_name"] =  unemployment_data["Area_name"].map(lambda x: x.split(',',1)[0])
unemployment_data.head()

,FIPStxt,State,Area_name,Rural_urban_continuum_code_2013,Urban_influence_code_2013,Metro_2013,Civilian_labor_force_2007,Employed_2007,Unemployed_2007,Unemployment_rate_2007,...,Civilian_labor_force_2016,Employed_2016,Unemployed_2016,Unemployment_rate_2016,Civilian_labor_force_2017,Employed_2017,Unemployed_2017,Unemployment_rate_2017,Median_Household_Income_2016,Med_HH_Income_Percent_of_State_Total_2016
2,1001,AL,Autauga County,2.0,2.0,1.0,"24,383","23,577",806,3.3,...,"25,918","24,593","1,325",5.1,25909,24908,1001,3.9,"$54,487",117.7
3,1003,AL,Baldwin County,3.0,2.0,1.0,"82,659","80,099","2,560",3.1,...,"90,500","85,656","4,844",5.4,91567,87915,3652,4.0,"$56,460",121.9
4,1005,AL,Barbour County,6.0,6.0,0.0,"10,334","9,684",650,6.3,...,"8,402","7,700",702,8.4,8236,7750,486,5.9,"$32,884",71.0
5,1007,AL,Bibb County,1.0,1.0,1.0,"8,791","8,432",359,4.1,...,"8,607","8,050",557,6.5,8506,8133,373,4.4,"$43,079",93.0
6,1009,AL,Blount County,1.0,1.0,1.0,"26,629","25,780",849,3.2,...,"24,576","23,248","1,328",5.4,24494,23509,985,4.0,"$47,213",102.0

In [5]:
population_data.head()

,FIPS,State,Area_Name,Rural-urban_Continuum Code_2003,Rural-urban_Continuum Code_2013,Urban_Influence_Code_2003,Urban_Influence_Code_2013,Economic_typology_2015,CENSUS_2010_POP,ESTIMATES_BASE_2010,...,R_DOMESTIC_MIG_2015,R_DOMESTIC_MIG_2016,R_DOMESTIC_MIG_2017,R_NET_MIG_2011,R_NET_MIG_2012,R_NET_MIG_2013,R_NET_MIG_2014,R_NET_MIG_2015,R_NET_MIG_2016,R_NET_MIG_2017
2,1001,AL,Autauga County,2.0,2.0,2.0,2.0,0.0,"54,571","54,571",...,-2.0,4.8,1.0,5.9,-6.1,-4.1,2.1,-1.7,5.1,1.3
3,1003,AL,Baldwin County,4.0,3.0,5.0,2.0,5.0,"182,265","182,265",...,17.0,20.5,22.4,16.3,17.2,22.6,20.4,17.9,21.3,23.2
4,1005,AL,Barbour County,6.0,6.0,6.0,6.0,3.0,"27,457","27,457",...,-16.2,-18.8,-19.0,0.3,-6.8,-8.0,-5.5,-16.4,-18.9,-19.2
5,1007,AL,Bibb County,1.0,1.0,1.0,1.0,0.0,"22,915","22,919",...,0.9,-1.4,-0.9,-5.0,-4.1,-5.9,1.2,1.8,-0.5,0.0
6,1009,AL,Blount County,1.0,1.0,1.0,1.0,0.0,"57,322","57,324",...,-1.6,-1.7,6.2,0.2,-1.4,-0.5,-1.8,-0.5,-0.7,7.3

In [6]:
# drop the ',' in values
population_data["POP_ESTIMATE_2017"] = population_data["POP_ESTIMATE_2017"].map(lambda x: x.replace(",",''))
population_data["POP_ESTIMATE_2016"] = population_data["POP_ESTIMATE_2016"].map(lambda x: x.replace(",",''))
population_data["POP_ESTIMATE_2015"] = population_data["POP_ESTIMATE_2015"].map(lambda x: x.replace(",",''))
population_data["POP_ESTIMATE_2014"] = population_data["POP_ESTIMATE_2014"].map(lambda x: x.replace(",",''))
population_data["POP_ESTIMATE_2013"] = population_data["POP_ESTIMATE_2013"].map(lambda x: x.replace(",",''))

In [7]:
print(poverty_data.shape, education_data.shape, unemployment_data.shape, population_data.shape)

(3142, 34) (3221, 47) (3219, 52) (3220, 133)

So the poverty data has least cities or counties

In [9]:
# Add features from the datasets we get
from copy import deepcopy
processed_all = deepcopy(poverty_data[["State", "Area_Name", "PCTPOVALL_2016", "PCTPOV017_2016", "MEDHHINC_2016"]])
processed_all = processed_all.rename(columns={'PCTPOVALL_2016':'pov_all', 
                              "PCTPOV017_2016":"pov_under17",  
                             "MEDHHINC_2016":"median_income"})
# convert poverty values to float or int (original is string)
processed_all["pov_all"] = processed_all["pov_all"].map(lambda x: float(x))
processed_all["pov_under17"] = processed_all["pov_under17"].map(lambda x: float(x))
# processed_all["median_income"] = processed_all["median_income"].map(lambda x: int(x.replace(",",'')))

# features from datasets other than poverty_data
processed_all["no_high_school"] = 0
processed_all["no_bachelor"] = 0
processed_all["unemployment"] = 0
processed_all["pop"] = 0

# convert other values to float or int
for i in processed_all["Area_Name"]:
    if i not in education_data["Area name"].values or i not in unemployment_data["Area_name"].values or i not in population_data["Area_Name"].values:
        processed_all.drop([processed_all[processed_all["Area_Name"]==i].index[0]],inplace=True)
for i in processed_all["Area_Name"]:
    processed_all.loc[processed_all["Area_Name"]==i, "no_high_school"] = float(education_data["Percent of adults with less than a high school diploma, 2012-2016"][education_data["Area name"]==i].values[0])
    processed_all.loc[processed_all["Area_Name"]==i, "no_bachelor"] = (float(education_data["Percent of adults with less than a high school diploma, 2012-2016"][education_data["Area name"]==i].values[0]) +
                                                                       float(education_data["Percent of adults with a high school diploma only, 2012-2016"][education_data["Area name"]==i].values[0]) +
                                                                       float(education_data["Percent of adults completing some college or associate's degree, 2012-2016"][education_data["Area name"]==i].values[0]))
    processed_all.loc[processed_all["Area_Name"]==i, "unemployment"] = (float(unemployment_data["Unemployment_rate_2017"][unemployment_data["Area_name"]==i].values[0])+
                                                                       float(unemployment_data["Unemployment_rate_2016"][unemployment_data["Area_name"]==i].values[0])+
                                                                       float(unemployment_data["Unemployment_rate_2015"][unemployment_data["Area_name"]==i].values[0])+
                                                                       float(unemployment_data["Unemployment_rate_2014"][unemployment_data["Area_name"]==i].values[0])+
                                                                       float(unemployment_data["Unemployment_rate_2013"][unemployment_data["Area_name"]==i].values[0]))/5
    processed_all.loc[processed_all["Area_Name"]==i, "pop"] = (int(population_data["POP_ESTIMATE_2017"][population_data["Area_Name"]==i].values[0]) +
                                                              int(population_data["POP_ESTIMATE_2016"][population_data["Area_Name"]==i].values[0]) +
                                                              int(population_data["POP_ESTIMATE_2015"][population_data["Area_Name"]==i].values[0]) +
                                                              int(population_data["POP_ESTIMATE_2014"][population_data["Area_Name"]==i].values[0]) +
                                                              int(population_data["POP_ESTIMATE_2013"][population_data["Area_Name"]==i].values[0]))/5
processed_all

,State,Area_Name,pov_all,pov_under17,median_income,no_high_school,no_bachelor,unemployment,pop
2,AL,Autauga County,14.0,19.0,"54,487",12.4,75.4,5.20,55035.8
3,AL,Baldwin County,12.0,18.0,"56,460",10.0,70.5,5.62,203360.0
4,AL,Barbour County,30.0,40.0,"32,884",26.2,87.1,8.80,26200.8
5,AL,Bibb County,20.0,28.0,"43,079",19.3,88.0,6.60,22579.6
6,AL,Blount County,14.0,19.0,"47,213",20.0,86.9,5.36,57666.8
7,AL,Bullock County,33.0,46.0,"34,278",33.4,89.7,7.60,10478.2
8,AL,Butler County,25.0,37.0,"35,409",18.9,83.9,7.84,20126.0
9,AL,Calhoun County,17.0,26.0,"41,778",17.7,82.4,7.06,115527.2
10,AL,Chambers County,20.0,33.0,"39,530",19.7,87.5,6.06,33893.6
11,AL,Cherokee County,17.0,28.0,"41,456",18.7,86.1,5.52,25855.0
12,AL,Chilton County,18.0,26.0,"44,188",19.9,85.2,5.68,43805.4
13,AL,Choctaw County,23.0,33.0,"32,691",21.1,88.0,8.42,13188.0
14,AL,Clarke County,29.0,39.0,"34,061",19.0,87.9,11.48,24624.8
15,AL,Clay County,19.0,28.0,"38,512",25.4,89.0,6.36,13407.4
16,AL,Cleburne County,17.0,25.0,"43,483",25.8,88.5,6.16,14939.4
17,AL,Coffee County,14.0,21.0,"48,632",14.9,76.3,5.96,51072.8
18,AL,Colbert County,17.0,25.0,"46,572",16.6,81.5,7.34,54434.8
19,AL,Conecuh County,28.0,44.0,"29,758",20.6,91.4,8.90,12649.4
20,AL,Coosa County,18.0,29.0,"36,441",27.1,90.1,7.12,10954.6
21,AL,Covington County,20.0,28.0,"35,010",19.1,85.1,6.98,37518.8
22,AL,Crenshaw County,21.0,29.0,"37,374",21.7,85.3,6.20,13865.6
23,AL,Cullman County,15.0,21.0,"41,543",17.8,85.0,5.30,81702.6
24,AL,Dale County,21.0,30.0,"40,523",14.2,84.0,6.14,49393.2
25,AL,Dallas County,35.0,58.0,"30,488",21.0,86.3,10.02,40755.0
26,AL,DeKalb County,21.0,31.0,"37,128",27.4,88.7,6.22,71194.0
27,AL,Elmore County,14.0,20.0,"54,553",13.2,77.7,5.06,80989.2
28,AL,Escambia County,23.0,31.0,"35,096",19.5,88.3,7.06,37620.6
29,AL,Etowah County,18.0,27.0,"40,972",17.5,83.4,6.22,103132.4
30,AL,Fayette County,20.0,29.0,"38,403",20.8,85.8,6.90,16657.0
31,AL,Franklin County,20.0,29.0,"37,049",24.3,87.6,6.36,31507.4
...,...,...,...,...,...,...,...,...,...
3163,WI,Washburn County,13.0,21.0,"46,989",8.2,78.4,5.50,15637.8
3164,WI,Washington County,6.0,6.0,"74,631",20.3,90.4,8.98,16745.6
3165,WI,Waukesha County,5.0,5.0,"82,080",4.1,58.4,4.04,396730.6
3166,WI,Waupaca County,11.0,15.0,"52,125",9.1,82.3,5.02,51650.8
3167,WI,Waushara County,14.0,24.0,"47,596",13.8,85.0,6.12,24170.2
3168,WI,Winnebago County,12.0,14.0,"57,003",12.6,77.6,7.74,287512.0
3169,WI,Wood County,10.0,14.0,"52,591",5.9,68.3,4.96,129504.2
3171,WY,Albany County,17.0,13.0,"47,355",7.3,60.3,4.68,308579.8
3172,WY,Big Horn County,11.0,14.0,"49,725",13.7,84.3,10.36,13290.2
3173,WY,Campbell County,8.0,9.0,"79,148",9.9,69.4,4.70,91803.8
3174,WY,Carbon County,12.0,12.0,"59,103",6.1,70.8,4.00,10466.0
3175,WY,Converse County,9.0,10.0,"71,517",9.8,84.5,4.26,14166.4
3176,WY,Crook County,8.0,9.0,"60,953",12.4,83.9,8.62,21717.4
3177,WY,Fremont County,17.0,20.0,"49,282",11.3,83.6,6.88,46600.8
3178,WY,Goshen County,15.0,16.0,"47,715",8.4,77.1,3.40,13478.8
3179,WY,Hot Springs County,14.0,18.0,"46,024",8.4,77.6,4.28,4741.0
3180,WY,Johnson County,9.0,10.0,"56,323",21.0,84.1,5.80,26155.2
3181,WY,Laramie County,10.0,11.0,"61,124",6.7,72.3,4.18,97030.8
3182,WY,Lincoln County,9.0,9.0,"63,907",20.9,92.1,6.08,13884.6
3183,WY,Natrona County,10.0,11.0,"60,559",8.3,77.7,5.18,81022.6
3184,WY,Niobrara County,14.0,15.0,"45,332",11.1,81.0,3.14,2479.2
3185,WY,Park County,11.0,13.0,"60,621",3.7,69.5,3.78,16900.4
3186,WY,Platte County,12.0,15.0,"54,588",4.7,59.3,4.32,96899.0
3187,WY,Sheridan County,9.0,11.0,"53,027",8.6,77.2,2.40,2497.4
3188,WY,Sublette County,7.0,7.0,"72,198",4.7,75.6,4.96,10036.8
3189,WY,Sweetwater County,10.0,9.0,"74,546",9.3,78.6,4.80,44527.4
3190,WY,Teton County,7.0,7.0,"84,118",8.8,60.0,3.78,10776.0
3191,WY,Uinta County,11.0,11.0,"64,713",10.4,81.8,5.06,20758.2
3192,WY,Washakie County,13.0,15.0,"49,533",12.6,79.0,4.42,8252.6
3193,WY,Weston County,11.0,14.0,"56,582",8.6,81.2,3.76,7116.8